package com.zzhalex233.alexscaves.server.misc;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.zzhalex233.alexscaves.AlexsCaves;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;

public class ACSoundRegistry {
    private static final Pattern SOUND_JSON_KEY = Pattern.compile("^\\s*\"([^\"]+)\"\\s*:\\s*\\{\\s*$");
    private static final Map<String, SoundEvent> MUTABLE_SOUNDS = new LinkedHashMap<>();

    public static final SoundEvent FUSION_MUSIC_DISC = sound("fusion_music_disc");
    public static final SoundEvent TASTY_MUSIC_DISC = sound("tasty_music_disc");
    public static final SoundEvent AMBER_STEP = sound("amber_step");
    public static final SoundEvent AMBER_PLACE = sound("amber_place");
    public static final SoundEvent AMBER_BREAK = sound("amber_break");
    public static final SoundEvent AMBER_BREAKING = sound("amber_breaking");
    public static final SoundEvent AMBER_MONOLITH_PLACE = sound("amber_monolith_place");
    public static final SoundEvent AMBER_MONOLITH_SUMMON = sound("amber_monolith_summon");
    public static final SoundEvent HAZMAT_BLOCK_STEP = sound("hazmat_block_step");
    public static final SoundEvent HAZMAT_BLOCK_PLACE = sound("hazmat_block_place");
    public static final SoundEvent HAZMAT_BLOCK_BREAK = sound("hazmat_block_break");
    public static final SoundEvent HAZMAT_BLOCK_BREAKING = sound("hazmat_block_breaking");
    public static final SoundEvent CINDER_BLOCK_STEP = sound("cinder_block_step");
    public static final SoundEvent CINDER_BLOCK_PLACE = sound("cinder_block_place");
    public static final SoundEvent CINDER_BLOCK_BREAK = sound("cinder_block_break");
    public static final SoundEvent CINDER_BLOCK_BREAKING = sound("cinder_block_breaking");
    public static final SoundEvent UNREFINED_WASTE_STEP = sound("unrefined_waste_step");
    public static final SoundEvent UNREFINED_WASTE_PLACE = sound("unrefined_waste_place");
    public static final SoundEvent UNREFINED_WASTE_BREAK = sound("unrefined_waste_break");
    public static final SoundEvent UNREFINED_WASTE_BREAKING = sound("unrefined_waste_breaking");
    public static final SoundEvent SULFUR_STEP = sound("sulfur_step");
    public static final SoundEvent SULFUR_PLACE = sound("sulfur_place");
    public static final SoundEvent SULFUR_BREAK = sound("sulfur_break");
    public static final SoundEvent SULFUR_BREAKING = sound("sulfur_breaking");
    public static final SoundEvent NEODYMIUM_STEP = sound("neodymium_step");
    public static final SoundEvent NEODYMIUM_PLACE = sound("neodymium_place");
    public static final SoundEvent NEODYMIUM_BREAK = sound("neodymium_break");
    public static final SoundEvent NEODYMIUM_BREAKING = sound("neodymium_breaking");
    public static final SoundEvent AZURE_NEODYMIUM_PUSH_LOOP = sound("azure_neodymium_push_loop");
    public static final SoundEvent SCARLET_NEODYMIUM_PULL_LOOP = sound("scarlet_neodymium_pull_loop");
    public static final SoundEvent RESITOR_SHIELD_AZURE_LOOP = sound("resistor_shield_azure_loop");
    public static final SoundEvent RESITOR_SHIELD_SCARLET_LOOP = sound("resistor_shield_scarlet_loop");
    public static final SoundEvent RESITOR_SHIELD_SLAM = sound("resistor_shield_slam");
    public static final SoundEvent RESITOR_SHIELD_SPIN = sound("resistor_shield_spin");
    public static final SoundEvent METAL_BARREL_LID = sound("metal_barrel_lid");
    public static final SoundEvent SOFT_CANDY_STEP = sound("soft_candy_step");
    public static final SoundEvent SOFT_CANDY_PLACE = sound("soft_candy_place");
    public static final SoundEvent SOFT_CANDY_BREAK = sound("soft_candy_break");
    public static final SoundEvent SOFT_CANDY_BREAKING = sound("soft_candy_breaking");
    public static final SoundEvent DENSE_CANDY_STEP = sound("dense_candy_step");
    public static final SoundEvent DENSE_CANDY_PLACE = sound("dense_candy_place");
    public static final SoundEvent DENSE_CANDY_BREAK = sound("dense_candy_break");
    public static final SoundEvent DENSE_CANDY_BREAKING = sound("dense_candy_breaking");
    public static final SoundEvent HARD_CANDY_STEP = sound("hard_candy_step");
    public static final SoundEvent HARD_CANDY_PLACE = sound("hard_candy_place");
    public static final SoundEvent HARD_CANDY_BREAK = sound("hard_candy_break");
    public static final SoundEvent HARD_CANDY_BREAKING = sound("hard_candy_breaking");
    public static final SoundEvent SQUISHY_CANDY_STEP = sound("squishy_candy_step");
    public static final SoundEvent SQUISHY_CANDY_PLACE = sound("squishy_candy_place");
    public static final SoundEvent SQUISHY_CANDY_BREAK = sound("squishy_candy_break");
    public static final SoundEvent SQUISHY_CANDY_BREAKING = sound("squishy_candy_breaking");
    public static final SoundEvent TRILOCARIS_HURT = sound("trilocaris_hurt");
    public static final SoundEvent TRILOCARIS_DEATH = sound("trilocaris_death");
    public static final SoundEvent TRILOCARIS_STEP = sound("trilocaris_step");
    public static final SoundEvent LANTERNFISH_HURT = sound("lanternfish_hurt");
    public static final SoundEvent LANTERNFISH_FLOP = sound("lanternfish_flop");
    public static final SoundEvent TRIPODFISH_HURT = sound("tripodfish_hurt");
    public static final SoundEvent TRIPODFISH_FLOP = sound("tripodfish_flop");
    public static final SoundEvent SEA_PIG_IDLE = sound("sea_pig_idle");
    public static final SoundEvent SEA_PIG_HURT = sound("sea_pig_hurt");
    public static final SoundEvent SEA_PIG_DEATH = sound("sea_pig_death");
    public static final SoundEvent SEA_PIG_EAT = sound("sea_pig_eat");
    public static final SoundEvent GOSSAMER_WORM_IDLE = sound("gossamer_worm_idle");
    public static final SoundEvent GOSSAMER_WORM_HURT = sound("gossamer_worm_hurt");
    public static final SoundEvent GOSSAMER_WORM_DEATH = sound("gossamer_worm_death");
    public static final SoundEvent SWEETISH_FISH_HURT = sound("sweetish_fish_hurt");
    public static final SoundEvent SWEETISH_FISH_FLOP = sound("sweetish_fish_flop");
    public static final SoundEvent GROTTOCERATOPS_IDLE = sound("grottoceratops_idle");
    public static final SoundEvent GROTTOCERATOPS_HURT = sound("grottoceratops_hurt");
    public static final SoundEvent GROTTOCERATOPS_DEATH = sound("grottoceratops_death");
    public static final SoundEvent GROTTOCERATOPS_CALL = sound("grottoceratops_call");
    public static final SoundEvent GROTTOCERATOPS_ATTACK = sound("grottoceratops_attack");
    public static final SoundEvent GROTTOCERATOPS_GRAZE = sound("grottoceratops_graze");
    public static final SoundEvent GROTTOCERATOPS_STEP = sound("grottoceratops_step");
    public static final SoundEvent PEWEN_BRANCH_BREAK = sound("pewen_branch_break");
    public static final SoundEvent RELICHEIRUS_IDLE = sound("relicheirus_idle");
    public static final SoundEvent RELICHEIRUS_HURT = sound("relicheirus_hurt");
    public static final SoundEvent RELICHEIRUS_DEATH = sound("relicheirus_death");
    public static final SoundEvent RELICHEIRUS_SCRATCH = sound("relicheirus_scratch");
    public static final SoundEvent RELICHEIRUS_STEP = sound("relicheirus_step");
    public static final SoundEvent RELICHEIRUS_TOPPLE = sound("relicheirus_topple");
    public static final SoundEvent VALLUMRAPTOR_IDLE = sound("vallumraptor_idle");
    public static final SoundEvent VALLUMRAPTOR_HURT = sound("vallumraptor_hurt");
    public static final SoundEvent VALLUMRAPTOR_DEATH = sound("vallumraptor_death");
    public static final SoundEvent VALLUMRAPTOR_CALL = sound("vallumraptor_call");
    public static final SoundEvent VALLUMRAPTOR_ATTACK = sound("vallumraptor_attack");
    public static final SoundEvent VALLUMRAPTOR_SCRATCH = sound("vallumraptor_scratch");
    public static final SoundEvent VALLUMRAPTOR_SLEEP = sound("vallumraptor_sleep");
    public static final SoundEvent SUBTERRANODON_IDLE = sound("subterranodon_idle");
    public static final SoundEvent SUBTERRANODON_HURT = sound("subterranodon_hurt");
    public static final SoundEvent SUBTERRANODON_DEATH = sound("subterranodon_death");
    public static final SoundEvent SUBTERRANODON_FLAP = sound("subterranodon_flap");
    public static final SoundEvent SUBTERRANODON_ATTACK = sound("subterranodon_attack");
    public static final SoundEvent CANDICORN_IDLE = sound("candicorn_idle");
    public static final SoundEvent CANDICORN_HURT = sound("candicorn_hurt");
    public static final SoundEvent CANDICORN_DEATH = sound("candicorn_death");
    public static final SoundEvent CANDICORN_STEP = sound("candicorn_step");
    public static final SoundEvent CANDICORN_GALLOP = sound("candicorn_gallop");
    public static final SoundEvent CANDICORN_CHARGE_START = sound("candicorn_charge_start");
    public static final SoundEvent CANDICORN_CHARGE_LOOP = sound("candicorn_charge_loop");
    public static final SoundEvent GUMMY_BEAR_IDLE = sound("gummy_bear_idle");
    public static final SoundEvent GUMMY_BEAR_HURT = sound("gummy_bear_hurt");
    public static final SoundEvent GUMMY_BEAR_DEATH = sound("gummy_bear_death");
    public static final SoundEvent GUMMY_BEAR_EAT = sound("gummy_bear_eat");
    public static final SoundEvent GUMMY_BEAR_SNORE = sound("gummy_bear_snore");
    public static final SoundEvent GUMMY_BEAR_STEP = sound("gummy_bear_step");
    public static final SoundEvent DEEP_ONE_IDLE = sound("deep_one_idle");
    public static final SoundEvent DEEP_ONE_HURT = sound("deep_one_hurt");
    public static final SoundEvent DEEP_ONE_DEATH = sound("deep_one_death");
    public static final SoundEvent DEEP_ONE_HOSTILE = sound("deep_one_hostile");
    public static final SoundEvent DEEP_ONE_ATTACK = sound("deep_one_attack");
    public static final SoundEvent DEEP_ONE_ADMIRE = sound("deep_one_admire");
    public static final SoundEvent DEEP_ONE_KNIGHT_IDLE = sound("deep_one_knight_idle");
    public static final SoundEvent DEEP_ONE_KNIGHT_HURT = sound("deep_one_knight_hurt");
    public static final SoundEvent DEEP_ONE_KNIGHT_DEATH = sound("deep_one_knight_death");
    public static final SoundEvent DEEP_ONE_KNIGHT_HOSTILE = sound("deep_one_knight_hostile");
    public static final SoundEvent DEEP_ONE_KNIGHT_ATTACK = sound("deep_one_knight_attack");
    public static final SoundEvent DEEP_ONE_KNIGHT_ADMIRE = sound("deep_one_knight_admire");
    public static final SoundEvent DEEP_ONE_MAGE_IDLE = sound("deep_one_mage_idle");
    public static final SoundEvent DEEP_ONE_MAGE_HURT = sound("deep_one_mage_hurt");
    public static final SoundEvent DEEP_ONE_MAGE_DEATH = sound("deep_one_mage_death");
    public static final SoundEvent DEEP_ONE_MAGE_HOSTILE = sound("deep_one_mage_hostile");
    public static final SoundEvent DEEP_ONE_MAGE_ATTACK = sound("deep_one_mage_attack");
    public static final SoundEvent DEEP_ONE_MAGE_ADMIRE = sound("deep_one_mage_admire");
    public static final SoundEvent MAGIC_CONCH_CAST = sound("magic_conch_cast");
    public static final SoundEvent MAGIC_CONCH_SUMMON = sound("magic_conch_summon");
    public static final SoundEvent SEA_STAFF_CAST = sound("sea_staff_cast");
    public static final SoundEvent SEA_STAFF_WOOSH = sound("sea_staff_woosh");
    public static final SoundEvent SEA_STAFF_HIT = sound("sea_staff_hit");
    public static final SoundEvent SEA_STAFF_BUBBLE = sound("sea_staff_bubble");
    public static final SoundEvent ORTHOLANCE_WAVE = sound("ortholance_wave");
    public static final SoundEvent MINE_GUARDIAN_IDLE = sound("mine_guardian_idle");
    public static final SoundEvent MINE_GUARDIAN_HURT = sound("mine_guardian_hurt");
    public static final SoundEvent MINE_GUARDIAN_DEATH = sound("mine_guardian_death");
    public static final SoundEvent MINE_GUARDIAN_EXPLODE = sound("mine_guardian_explode");
    public static final SoundEvent MINE_GUARDIAN_LAND_IDLE = sound("mine_guardian_land_idle");
    public static final SoundEvent MINE_GUARDIAN_LAND_HURT = sound("mine_guardian_land_hurt");
    public static final SoundEvent MINE_GUARDIAN_LAND_DEATH = sound("mine_guardian_land_death");
    public static final SoundEvent MINE_GUARDIAN_LAND_EXPLODE = sound("mine_guardian_land_explode");
    public static final SoundEvent MINE_GUARDIAN_SCAN = sound("mine_guardian_scan");
    public static final SoundEvent MINE_GUARDIAN_FLOP = sound("mine_guardian_flop");
    public static final SoundEvent ACID_BURN = sound("acid_burn");
    public static final SoundEvent ACID_CORROSION = sound("acid_corrosion");
    public static final SoundEvent ACID_IDLE = sound("acid_idle");
    public static final SoundEvent ACID_SWIM = sound("acid_swim");
    public static final SoundEvent ACID_SUBMERGE = sound("acid_submerge");
    public static final SoundEvent ACID_UNSUBMERGE = sound("acid_unsubmerge");
    public static final SoundEvent RADGILL_HURT = sound("radgill_hurt");
    public static final SoundEvent RADGILL_FLOP = sound("radgill_flop");
    public static final SoundEvent GAMMAROACH_IDLE = sound("gammaroach_idle");
    public static final SoundEvent GAMMAROACH_HURT = sound("gammaroach_hurt");
    public static final SoundEvent GAMMAROACH_DEATH = sound("gammaroach_death");
    public static final SoundEvent GAMMAROACH_ATTACK = sound("gammaroach_attack");
    public static final SoundEvent GAMMAROACH_SPRAY = sound("gammaroach_spray");
    public static final SoundEvent GAMMAROACH_STEP = sound("gammaroach_step");
    public static final SoundEvent RAYCAT_IDLE = sound("raycat_idle");
    public static final SoundEvent RAYCAT_TAME_IDLE = sound("raycat_tame_idle");
    public static final SoundEvent RAYCAT_HURT = sound("raycat_hurt");
    public static final SoundEvent RAYCAT_EAT = sound("raycat_eat");
    public static final SoundEvent RAYCAT_ABSORB = sound("raycat_absorb");
    public static final SoundEvent NUCLEEPER_IDLE = sound("nucleeper_idle");
    public static final SoundEvent NUCLEEPER_HURT = sound("nucleeper_hurt");
    public static final SoundEvent NUCLEEPER_DEATH = sound("nucleeper_death");
    public static final SoundEvent NUCLEEPER_STEP = sound("nucleeper_step");
    public static final SoundEvent NUCLEEPER_CHARGE = sound("nucleeper_charge");
    public static final SoundEvent NUCLEAR_EXPLOSION = sound("nuclear_explosion");
    public static final SoundEvent LARGE_NUCLEAR_EXPLOSION = sound("large_nuclear_explosion");
    public static final SoundEvent NUCLEAR_EXPLOSION_RUMBLE = sound("nuclear_explosion_rumble");
    public static final SoundEvent NUCLEAR_EXPLOSION_RINGING = sound("nuclear_explosion_ringing");
    public static final SoundEvent NUCLEAR_FURNACE_ACTIVE = sound("nuclear_furnace_active");
    public static final SoundEvent NUCLEAR_FURNACE_ACTIVE_SUBCRITICAL = sound("nuclear_furnace_active_subcritical");
    public static final SoundEvent NUCLEAR_FURNACE_ACTIVE_CRITICAL = sound("nuclear_furnace_active_critical");
    public static final SoundEvent NUCLEAR_FURNACE_ACTIVE_SUPERCRITICAL = sound("nuclear_furnace_active_supercritical");
    public static final SoundEvent NUCLEAR_SIREN = sound("nuclear_siren");
    public static final SoundEvent RAYGUN_LOOP = sound("raygun_loop");
    public static final SoundEvent RAYGUN_RELOAD = sound("raygun_reload");
    public static final SoundEvent RAYGUN_EMPTY = sound("raygun_empty");
    public static final SoundEvent RAYGUN_START = sound("raygun_start");
    public static final SoundEvent BRAINIAC_IDLE = sound("brainiac_idle");
    public static final SoundEvent BRAINIAC_HURT = sound("brainiac_hurt");
    public static final SoundEvent BRAINIAC_DEATH = sound("brainiac_death");
    public static final SoundEvent BRAINIAC_STEP = sound("brainiac_step");
    public static final SoundEvent BRAINIAC_ATTACK = sound("brainiac_attack");
    public static final SoundEvent BRAINIAC_LICK = sound("brainiac_lick");
    public static final SoundEvent BRAINIAC_THROW = sound("brainiac_throw");
    public static final SoundEvent CORRODENT_IDLE = sound("corrodent_idle");
    public static final SoundEvent CORRODENT_HURT = sound("corrodent_hurt");
    public static final SoundEvent CORRODENT_DEATH = sound("corrodent_death");
    public static final SoundEvent CORRODENT_ATTACK = sound("corrodent_attack");
    public static final SoundEvent CORRODENT_TEETH = sound("corrodent_teeth");
    public static final SoundEvent CORRODENT_DIG_LOOP = sound("corrodent_dig_loop");
    public static final SoundEvent CORRODENT_DIG_STOP = sound("corrodent_dig_stop");
    public static final SoundEvent VESPER_IDLE = sound("vesper_idle");
    public static final SoundEvent VESPER_QUIET_IDLE = sound("vesper_quiet_idle");
    public static final SoundEvent VESPER_HURT = sound("vesper_hurt");
    public static final SoundEvent VESPER_DEATH = sound("vesper_death");
    public static final SoundEvent VESPER_FLAP = sound("vesper_flap");
    public static final SoundEvent VESPER_SCREAM = sound("vesper_scream");
    public static final SoundEvent GLOOMOTH_HURT = sound("gloomoth_hurt");
    public static final SoundEvent GLOOMOTH_DEATH = sound("gloomoth_death");
    public static final SoundEvent GLOOMOTH_FLAP = sound("gloomoth_flap");
    public static final SoundEvent WATCHER_IDLE = sound("watcher_idle");
    public static final SoundEvent WATCHER_HURT = sound("watcher_hurt");
    public static final SoundEvent WATCHER_DEATH = sound("watcher_death");
    public static final SoundEvent WATCHER_ATTACK = sound("watcher_attack");
    public static final SoundEvent WATCHER_SCARE = sound("watcher_scare");
    public static final SoundEvent WATCHER_SPAWN = sound("watcher_spawn");
    public static final SoundEvent HOLOGRAM_LOOP = sound("hologram_loop");
    public static final SoundEvent HOLOGRAM_STOP = sound("hologram_stop");
    public static final SoundEvent QUARRY_CRUSH = sound("quarry_crush");
    public static final SoundEvent NOTOR_IDLE = sound("notor_idle");
    public static final SoundEvent NOTOR_HURT = sound("notor_hurt");
    public static final SoundEvent NOTOR_DEATH = sound("notor_death");
    public static final SoundEvent NOTOR_FLYING = sound("notor_flying");
    public static final SoundEvent TELETOR_IDLE = sound("teletor_idle");
    public static final SoundEvent TELETOR_HURT = sound("teletor_hurt");
    public static final SoundEvent TELETOR_DEATH = sound("teletor_death");
    public static final SoundEvent TELETOR_FLOAT = sound("teletor_float");
    public static final SoundEvent BOUNDROID_IDLE = sound("boundroid_idle");
    public static final SoundEvent BOUNDROID_HURT = sound("boundroid_hurt");
    public static final SoundEvent BOUNDROID_DEATH = sound("boundroid_death");
    public static final SoundEvent BOUNDROID_SLAM = sound("boundroid_slam");
    public static final SoundEvent BOUNDROID_DAZED = sound("boundroid_dazed");
    public static final SoundEvent BOUNDROID_CHAIN_LOOP = sound("boundroid_chain_loop");
    public static final SoundEvent UNDERZEALOT_IDLE = sound("underzealot_idle");
    public static final SoundEvent UNDERZEALOT_HURT = sound("underzealot_hurt");
    public static final SoundEvent UNDERZEALOT_DEATH = sound("underzealot_death");
    public static final SoundEvent UNDERZEALOT_ATTACK = sound("underzealot_attack");
    public static final SoundEvent UNDERZEALOT_CHANT = sound("underzealot_chant");
    public static final SoundEvent UNDERZEALOT_DIG = sound("underzealot_dig");
    public static final SoundEvent UNDERZEALOT_TRANSFORMATION = sound("underzealot_transformation");
    public static final SoundEvent FORSAKEN_IDLE = sound("forsaken_idle");
    public static final SoundEvent FORSAKEN_HURT = sound("forsaken_hurt");
    public static final SoundEvent FORSAKEN_DEATH = sound("forsaken_death");
    public static final SoundEvent FORSAKEN_SPAWN = sound("forsaken_spawn");
    public static final SoundEvent FORSAKEN_SCREECH = sound("forsaken_screech");
    public static final SoundEvent FORSAKEN_AOE = sound("forsaken_aoe");
    public static final SoundEvent FORSAKEN_LEAP = sound("forsaken_leap");
    public static final SoundEvent FORSAKEN_GRAB = sound("forsaken_grab");
    public static final SoundEvent FORSAKEN_BITE = sound("forsaken_bite");
    public static final SoundEvent FORSAKEN_STEP = sound("forsaken_step");
    public static final SoundEvent DESOLATE_DAGGER_SUMMON = sound("desolate_dagger_summon");
    public static final SoundEvent DESOLATE_DAGGER_HIT = sound("desolate_dagger_hit");
    public static final SoundEvent DREADBOW_RELEASE = sound("dreadbow_release");
    public static final SoundEvent DREADBOW_RAIN = sound("dreadbow_rain");
    public static final SoundEvent TOTEM_OF_POSSESSION_USE = sound("totem_of_possession_use");
    public static final SoundEvent PURPLE_SODA_IDLE = sound("purple_soda_idle");
    public static final SoundEvent PURPLE_SODA_SWIM = sound("purple_soda_swim");
    public static final SoundEvent PURPLE_SODA_SUBMERGE = sound("purple_soda_submerge");
    public static final SoundEvent PURPLE_SODA_UNSUBMERGE = sound("purple_soda_unsubmerge");
    public static final SoundEvent RAINBOUNCE_BOOTS_BOUNCE = sound("rainbounce_boots_bounce");
    public static final SoundEvent LIMESTONE_SPEAR_THROW = sound("limestone_spear_throw");
    public static final SoundEvent LIMESTONE_SPEAR_HIT = sound("limestone_spear_hit");
    public static final SoundEvent EXTINCTION_SPEAR_THROW = sound("extinction_spear_throw");
    public static final SoundEvent EXTINCTION_SPEAR_HIT = sound("extinction_spear_hit");
    public static final SoundEvent EXTINCTION_SPEAR_SUMMON = sound("extinction_spear_summon");
    public static final SoundEvent FROSTMINT_SPEAR_THROW = sound("frostmint_spear_throw");
    public static final SoundEvent FROSTMINT_SPEAR_HIT = sound("frostmint_spear_hit");
    public static final SoundEvent TEPHRA_HIT = sound("tephra_hit");
    public static final SoundEvent SEEKING_ARROW_HIT = sound("seeking_arrow_hit");
    public static final SoundEvent SEEKING_ARROW_LOCKON = sound("seeking_arrow_lockon");
    public static final SoundEvent GALENA_GAUNTLET_STOP = sound("galena_gauntlet_stop");
    public static final SoundEvent GALENA_GAUNTLET_USE_LOOP = sound("galena_gauntlet_use_loop");
    public static final SoundEvent SUBMARINE_PLACE = sound("submarine_place");
    public static final SoundEvent SUBMARINE_HIT = sound("submarine_hit");
    public static final SoundEvent SUBMARINE_CREAK = sound("submarine_creak");
    public static final SoundEvent SUBMARINE_REPAIR = sound("submarine_repair");
    public static final SoundEvent SUBMARINE_DESTROY = sound("submarine_destroy");
    public static final SoundEvent SUBMARINE_LIGHT_ON = sound("submarine_light_on");
    public static final SoundEvent SUBMARINE_LIGHT_OFF = sound("submarine_light_off");
    public static final SoundEvent SUBMARINE_MOVE_LOOP = sound("submarine_move_loop");
    public static final SoundEvent SUBMARINE_SONAR = sound("submarine_sonar");
    public static final SoundEvent CAVE_BOOK_OPEN = sound("cave_book_open");
    public static final SoundEvent CAVE_BOOK_CLOSE = sound("cave_book_close");
    public static final SoundEvent CAVE_BOOK_TURN = sound("cave_book_turn");
    public static final SoundEvent SPELUNKERY_TABLE_TABLET_INSERT = sound("spelunkery_table_tablet_insert");
    public static final SoundEvent SPELUNKERY_TABLE_TABLET_REMOVE = sound("spelunkery_table_tablet_remove");
    public static final SoundEvent SPELUNKERY_TABLE_PAPER_INSERT = sound("spelunkery_table_paper_insert");
    public static final SoundEvent SPELUNKERY_TABLE_PAPER_REMOVE = sound("spelunkery_table_paper_remove");
    public static final SoundEvent SPELUNKERY_TABLE_CODEX_REMOVE = sound("spelunkery_table_codex_remove");
    public static final SoundEvent SPELUNKERY_TABLE_SUCCESS = sound("spelunkery_table_success");
    public static final SoundEvent SPELUNKERY_TABLE_SUCCESS_COMPLETE = sound("spelunkery_table_success_complete");
    public static final SoundEvent SPELUNKERY_TABLE_CRACK = sound("spelunkery_table_crack");
    public static final SoundEvent SPELUNKERY_TABLE_FAIL = sound("spelunkery_table_fail");
    public static final SoundEvent SPELUNKERY_TABLE_ATTEMPT_FAIL = sound("spelunkery_table_attempt_fail");
    public static final SoundEvent CONVERSION_CRUCIBLE_ADD = sound("conversion_crucible_add");
    public static final SoundEvent CONVERSION_CRUCIBLE_ACTIVATE = sound("conversion_crucible_activate");
    public static final SoundEvent CONVERSION_CRUCIBLE_CONVERT = sound("conversion_crucible_convert");
    public static final SoundEvent CANIAC_IDLE = sound("caniac_idle");
    public static final SoundEvent CANIAC_HURT = sound("caniac_hurt");
    public static final SoundEvent CANIAC_DEATH = sound("caniac_death");
    public static final SoundEvent CANIAC_ATTACK = sound("caniac_attack");
    public static final SoundEvent CANIAC_SWING = sound("caniac_swing");
    public static final SoundEvent CARAMEL_CUBE_ATTACK = sound("caramel_cube_attack");
    public static final SoundEvent CARAMEL_CUBE_SMALL = sound("caramel_cube_small");
    public static final SoundEvent CARAMEL_CUBE_BIG = sound("caramel_cube_big");
    public static final SoundEvent GUMBEEPER_HURT = sound("gumbeeper_hurt");
    public static final SoundEvent GUMBEEPER_DEATH = sound("gumbeeper_death");
    public static final SoundEvent GUMBEEPER_EXPLODE = sound("gumbeeper_explode");
    public static final SoundEvent GUMBALL_LAUNCH = sound("gumball_launch");
    public static final SoundEvent GUMBALL_HIT = sound("gumball_hit");
    public static final SoundEvent GUMBALL_BOUNCE = sound("gumball_bounce");
    public static final SoundEvent SHOTGUM_SHOOT = sound("shotgum_shoot");
    public static final SoundEvent SHOTGUM_RELOAD = sound("shotgum_reload");
    public static final SoundEvent SHOTGUM_EMPTY = sound("shotgum_empty");
    public static final SoundEvent SUGAR_STAFF_CAST_PEPPERMINT = sound("sugar_staff_cast_peppermint");
    public static final SoundEvent SUGAR_STAFF_CAST_HEX = sound("sugar_staff_cast_hex");
    public static final SoundEvent CANDY_CANE_HOOK_LAUNCH = sound("candy_cane_hook_launch");
    public static final SoundEvent CANDY_CANE_HOOK_REEL = sound("candy_cane_hook_reel");
    public static final SoundEvent GINGERBREAD_MAN_IDLE = sound("gingerbread_man_idle");
    public static final SoundEvent GINGERBREAD_MAN_HURT = sound("gingerbread_man_hurt");
    public static final SoundEvent GINGERBREAD_MAN_DEATH = sound("gingerbread_man_death");
    public static final SoundEvent GINGERBREAD_MAN_ATTACK = sound("gingerbread_man_attack");
    public static final SoundEvent GINGERBREAD_MAN_TALK = sound("gingerbread_man_talk");
    public static final SoundEvent GUM_WORM_IDLE = sound("gum_worm_idle");
    public static final SoundEvent GUM_WORM_HURT = sound("gum_worm_hurt");
    public static final SoundEvent GUM_WORM_DEATH = sound("gum_worm_death");
    public static final SoundEvent GUM_WORM_ATTACK = sound("gum_worm_attack");
    public static final SoundEvent GUM_WORM_DIG_LOOP = sound("gum_worm_dig_loop");
    public static final SoundEvent GUM_WORM_DIG_STOP = sound("gum_worm_dig_stop");
    public static final SoundEvent FERROUSLIME_HURT = sound("ferrouslime_hurt");
    public static final SoundEvent FERROUSLIME_DEATH = sound("ferrouslime_death");
    public static final SoundEvent FERROUSLIME_COMBINE = sound("ferrouslime_combine");
    public static final SoundEvent FERROUSLIME_MOVE_LOOP = sound("ferrouslime_move_loop");
    public static final SoundEvent MAGNETRON_IDLE = sound("magnetron_idle");
    public static final SoundEvent MAGNETRON_HURT = sound("magnetron_hurt");
    public static final SoundEvent MAGNETRON_DEATH = sound("magnetron_death");
    public static final SoundEvent MAGNETRON_ATTACK = sound("magnetron_attack");
    public static final SoundEvent MAGNETRON_ROLL = sound("magnetron_roll");
    public static final SoundEvent MAGNETRON_STEP = sound("magnetron_step");
    public static final SoundEvent MAGNETRON_ASSEMBLE = sound("magnetron_assemble");
    public static final SoundEvent HULLBREAKER_IDLE = sound("hullbreaker_idle");
    public static final SoundEvent HULLBREAKER_HURT = sound("hullbreaker_hurt");
    public static final SoundEvent HULLBREAKER_DEATH = sound("hullbreaker_death");
    public static final SoundEvent HULLBREAKER_LAND_IDLE = sound("hullbreaker_land_idle");
    public static final SoundEvent HULLBREAKER_LAND_HURT = sound("hullbreaker_land_hurt");
    public static final SoundEvent HULLBREAKER_LAND_DEATH = sound("hullbreaker_land_death");
    public static final SoundEvent HULLBREAKER_ATTACK = sound("hullbreaker_attack");
    public static final SoundEvent PRIMITIVE_CLUB_HIT = sound("primitive_club_hit");
    public static final SoundEvent PRIMITIVE_CLUB_MISS = sound("primitive_club_miss");

    public static final List<SoundEvent> SOUNDS = Collections.unmodifiableList(allSounds());

    private static SoundEvent sound(String name) {
        SoundEvent existing = MUTABLE_SOUNDS.get(name);
        if (existing != null) {
            return existing;
        }
        ResourceLocation id = new ResourceLocation(AlexsCaves.MODID, name);
        SoundEvent sound = new SoundEvent(id).setRegistryName(id);
        MUTABLE_SOUNDS.put(name, sound);
        return sound;
    }

    private static List<SoundEvent> allSounds() {
        try (InputStream input = ACSoundRegistry.class.getClassLoader().getResourceAsStream("assets/alexscaves/sounds.json")) {
            if (input != null) {
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        Matcher matcher = SOUND_JSON_KEY.matcher(line);
                        if (matcher.matches()) {
                            sound(matcher.group(1));
                        }
                    }
                }
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to read alexscaves sounds.json", exception);
        }
        return new ArrayList<>(MUTABLE_SOUNDS.values());
    }
}
